mod arithmetic_gate_test;
mod component_provider_test;
mod entity_type_provider_test;

mod arithmetic_operation_behaviour_test;
mod arithmetic_operation_function_test;

mod arithmetic_gate_behaviour_test;
mod arithmetic_gate_function_test;
