name: Code Coverage

on:
  push:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/coverage.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/coverage.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov-tarpaulin:
    name: Generate code coverage
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.22.0'
          args: --all-features
      # Note: closed-source code needs to provide a token,
      # but open source code does not.
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5.0.2
        with:
          verbose: true
          fail_ci_if_error: true
